# Generated by Django 4.1 on 2022-10-25 12:55

from django.conf import settings
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Please enter a value.', 'unique': 'Please enter a unique name.'}, help_text='Name should be unique.', max_length=150)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[products.models.check_price])),
                ('category', models.CharField(choices=[('el', 'Electronics'), ('gr', 'Groceries')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products-imgs')),
                ('description', models.TextField(blank=True, default='This is a product', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['price'],
            },
        ),
    ]
