# Generated by Django 4.1 on 2022-11-05 13:27

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_user_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[products.models.check_price]),
        ),
    ]
