# Generated by Django 4.1 on 2022-09-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_updated_alter_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('groceris', 'Groceries')], default='electronics', max_length=20),
            preserve_default=False,
        ),
    ]
