# Generated by Django 4.1 on 2022-09-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('el', 'Electronics'), ('gr', 'Groceries')], max_length=20),
        ),
    ]
