# Generated by Django 4.1 on 2022-10-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
