# Generated by Django 4.1 on 2022-10-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
